const ACTIVE_EMAILS = new Set([
  'pooja@themavericksindia.com',
  'manvi@themavericksindia.com',
  'chetan@themavericksindia.com',
  'alisha@themavericksindia.com',
  'srishtee@themavericksindia.com',
  'tonmoyee@themavericksindia.com',
  'udita@themavericksindia.com',
  'gaurav@themavericksindia.com',
  'ananya@themavericksindia.com',
  'akshay@themavericksindia.com',
  'kashish@themavericksindia.com',
  'laveena@themavericksindia.com',
  'rohan.jolly@themavericksindia.com',
  'pavithra@themavericksindia.com',
  'avinash@themavericksindia.com',
  'smita@themavericksindia.com',
  'muskaan@themavericksindia.com',
  'triyanshi@themavericksindia.com',
  'smriti@themavericksindia.com',
  'archana@themavericksindia.com',
  'varun@themavericksindia.com',
  'muskaan.bhardwaj@themavericksindia.com',
  'ishmeet@themavericksindia.com',
  'chhavi.a@themavericksindia.com',
  'ritika@themavericksindia.com',
  'avarna@themavericksindia.com',
  'kyle@themavericksindia.com',
  'brinda@themavericksindia.com',
  'mitali.p@themavericksindia.com',
  'sushant@themavericksindia.com',
  'mahek@themavericksindia.com',
  'vishakha@themavericksindia.com',
  'vanshika@themavericksindia.com',
  'aditya.s@themavericksindia.com',
  'vibhu@themavericksindia.com',
  'ariba@themavericksindia.com',
  'kavita@themavericksindia.com',
  'drishti.c@themavericksindia.com',
  'snigdha@themavericksindia.com',
  'grishma@themavericksindia.com',
  'riya.rupani@themavericksindia.com',
  'rishika@themavericksindia.com',
  'harshita@themavericksindia.com',
  'mansi@themavericksindia.com',
  'harprateek@themavericksindia.com',
  'khushi@themavericksindia.com',
  'pratyasha@themavericksindia.com',
  'shinjini@themavericksindia.com',
  'neha@themavericksindia.com',
  'anil@themavericksindia.com',
  'priyadarshini@themavericksindia.com',
  'ila@themavericksindia.com',
  'vibhuti@themavericksindia.com',
  'ritik@themavericksindia.com',
  'sanya.p@themavericksindia.com',
  'arunkumar@themavericksindia.com',
  'divyanshsharma@themavericksindia.com',
  'satyam.singh@themavericksindia.com',
  'muskaan.harjai@themavericksindia.com',
  'aashna@themavericksindia.com',
  'samrat@themavericksindia.com',
  'bhavya@themavericksindia.com',
  'manaswi@themavericksindia.com',
  'abhilasha@themavericksindia.com',
  'apurva@themavericksindia.com',
  'mohamed.hisham@themavericksindia.com',
  'tech@themavericksindia.com',
  'surya@themavericksindia.com',
  'srishti.chanda@themavericksindia.com',
  'anoushka.aristotle@themavericksindia.com',
  'mahek.chacha@themavericksindia.com',
  'shreshtha.chaturvedi@themavericksindia.com',
  'ridhi@themavericksindia.com',
  'joyeta.debnath@themavericksindia.com',
  'jayeeta@themavericksindia.com', // Included to ensure legacy match for Jayeeta
  'rajvi@themavericksindia.com',
  'jyoshitha@themavericksindia.com',
  'nikita.hooper@themavericksindia.com',
  'disha.kalra@themavericksindia.com'
]);

export const isActiveUser = (email: string | null | undefined): boolean => {
  if (!email) return false;
  return ACTIVE_EMAILS.has(email.trim().toLowerCase());
};

export const getActiveEmailsList = (): string[] => {
  return Array.from(ACTIVE_EMAILS);
};
